### ISSUE TITLE
Good example of comments in code?

### ISSUE THREAD

**Issue by iteles** [dwyl/definition-of-done#3]
The definition of **well commented code** needs to be provided as @rjmk [pointed out](https://github.com/dwyl/summer-2015/issues/22#issuecomment-127175805).

**Comment by iteles** [comment]
Your code _should_ be self-explanatory, but sometimes you need to add in some comments to make it so. 

A good example of this is when some function is performed that has an impact elsewhere in the code that might not be immediately obvious.
_In JavaScript:_

<img width="494" alt="example-commented-code" src="https://cloud.githubusercontent.com/assets/4185328/9105441/c085acd0-3c0f-11e5-9664-ceb006433f82.png">

_In CSS:_

``` css
.article {
  position: relative; /*contains `.quote` which is positioned absolutely*/
  ...
}
```
